version: '3.9'

services:
  frontend:
    build: ./client
    environment:
      - NEXT_PUBLIC_SERVER=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:RogexJ48@database:5432/room_allocation?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - JWT_SECRET=your_secret_here
      - NODE_ENV=development
      - PORT=5000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - database
      - redis

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=RogexJ48
      - POSTGRES_DB=room_allocation
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
