version: '3.9'

services:
  frontend:
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - database
      - redis
    restart: always

  database:
    image: postgres:15
    #ports:
     # - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=RogexJ48
      - POSTGRES_DB=room_allocation
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    #ports:
     # - "6379:6379"
     # - "8001:8001"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
