version: '3.9'

services:
  frontend:
    build: ./client
    environment:
      - NEXT_PUBLIC_SERVER=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    
  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:RogexJ48@database:5432/room_allocation?schema=public
      - NEXTAUTH_URL="http://localhost:3000"
      - JWT_SECRET="5d359b41c97618ff47f5ccc37aa212a2d05a10c395c5a1377393322d28dbb893"
      - NODE_ENV="development"
      - ADMIN_EMAIL="adityaparthik@gmail.com"
      - GOOGLE_CLIENT_ID="1031797182637-sc5rr1qft894cc4ajjvt0kpu4j88h86i.apps.googleusercontent.com"
      - GOOGLE_CLIENT_SECRET="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"
      - PORT=5000
      - SESSION_SECRET="i_love_to_eat_rice_with_salt"
      - GOOGLE_REDIRECT_URI="http://localhost:5000/auth/google/callback"
    
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RogexJ48
      POSTGRES_DB: room_allocation
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - D:/Room_alloca_db:/var/lib/postgresql/data